apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaling
metadata:
  name: my-hpa
  labels:
    name: my-app
spec:
  scaleTargetRef:
    apiversion: app/v1
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 2
  metric:
    - type: cpu
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50
        